### ISSUE TITLE
Ask about x-printer

### ISSUE THREAD

**Issue by ice2009** [alpha3141/X_printer#1]
Hello Malt :) 

I ask when you planned public files about this printer ? I mean parts for cut or cnc :) 

Thank's

**Comment by alpha3141** [comment]
Hello, ice2009
I could release the prototype files if you want (from the current built). My problem is that until now, I still have some proprietary 3D-models in my design from which I do not know the licensing terms yet. (Linear Rails + ballscrew + nema 17). As a consequence, I can only upload each part by itself instead of the whole assembly.

**Comment by ice2009** [comment]
It is possible send me cad files for cnc cut and stl files ? I use own electronic :) could you send me files to mail? Thank's

**Comment by madhunm** [comment]
> Hello, ice2009
> I could release the prototype files if you want (from the current built). My problem is that until now, I still have some proprietary 3D-models in my design from which I do not know the licensing terms yet. (Linear Rails + ballscrew + nema 17). As a consequence, I can only upload each part by itself instead of the whole assembly.

Why don't you release the parts you have designed? With a link to where you downloaded the proprietary models from?

**Comment by alpha3141** [comment]
That's what I tried to write earlier, just wanted to point out that I can only publish the parts and not the whole 3d printer model in one file. (which would be more useful for modification/overview.) I have to clean up / rename the files, try to upload them by the end of this week.

**Comment by ice2009** [comment]
Hello :) thank's i wait for your update :)

**Comment by ice2009** [comment]
Hello :) thank's for sharing your alu files :) It's possible share all stl files (bearing holder and etc)? Thank's

**Comment by alpha3141** [comment]
Yes, of course. These are not all files yet. I will add the others in the next days.

**Comment by ice2009** [comment]
Thank's a lot i waitting for you :)

**Comment by ice2009** [comment]
Hello :) Any update ? :)

**Comment by alpha3141** [comment]
Have uploaded the whole assembly in on file.
